baseURL = "https://prestonbernstein.com"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Preston Bernstein's Blog" 
    description = "A personal website"
    favicon = ""
    message = "COMING SOON!" 
    release = "August 30, 2024" 
    background = "" 

socialIcons = [
    {name = "email", url = "contact@prestonbernstein.com"},
    {name = "github", url = "https://github.com/preston-bernstein"},
    {name = "linkedin", url = "https://linkedin.com/in/prestonbernstein"},    
] 
