name = "pres-ber-blog"
license = "CC BY-NC-ND"
licenselink = "https://github.com/preston-bernstein/pres-ber-blog/blob/main/LICENSE"
description = "pres-ber-blog is a personal blog built with Hugo and TailwindCSS."
homepage = "https://github.com/preston-bernstein/pres-ber-blog"
demosite = "https://prestonbernstein.com"
min_version = "0.124.1"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name ="DigitalMast"
homepage = "https://digitalmast.tech"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
