name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.125.7
  SITE_BASEURL: https://www.prestonbernstein.com

jobs:
######################################################################
# build & deploy the site
######################################################################
build-deploy:
name: Build and deploy
if: "!contains(github.event.head_commit.message,'[skip-ci]')"
runs-on: ubuntu-latest
steps:
######################################################################
# checkout full codebase
######################################################################
- name: Checkout repo codebase
  uses: actions/checkout@v4.1.4
  with:
    fetch-depth: 1
    clean: true
    submodules: false
######################################################################
# download & install Hugo (line break added in URL for readability)
######################################################################
- name: Download Hugo v${{ env.HUGO_VERSION }} Linux x64
  run: "wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}
  /hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb -O hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb"
- name: Install Hugo
  run: sudo dpkg -i hugo*.deb
######################################################################
# build site with Hugo
######################################################################
- name: Build site with Hugo
  run: hugo --baseUrl '${{ env.SITE_BASEURL }}'
######################################################################
# deploy site with Hugo deploy comment (only deploys diff)
######################################################################
- name: Deploy build to static site
  run: hugo deploy --maxDeletes -1
  env:
    AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
    AZURE_STORAGE_KEY: ${{ secrets.LIVE_AZURE_STORAGE_KEY }}

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.4
    - name: Checkout repository

    - uses: peaceiris/action-hugo@v3.0.0
    - name: Set up Hugo
      with:
        hugo-version: 'latest'
        
    - name: Build Hugo Site
      run: hugo --minify

    - name: Upload site
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: 'public/'
        target: '/path/to/cpanel/website/public_html/'
